# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180225_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='not_text',
            field=models.CharField(default='Expired!', max_length=500),
        ),
    ]
