# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notification_not_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='not_text',
            new_name='notify_text',
        ),
    ]
