# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180225_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notify_text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='days_remaining',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is read?'),
        ),
        migrations.AddField(
            model_name='notification',
            name='licence_type',
            field=models.CharField(default='7', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='truck_id',
            field=models.IntegerField(default=-1),
        ),
    ]
