# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_auto_20180225_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='truck_id',
            field=models.ForeignKey(db_column='truck_id', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Truck'),
        ),
    ]
