# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180225_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
